### ISSUE TITLE
saltyrtc.org Website

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#101]
I'd suggest either something with a static site generator (e.g. http://blog.getpelican.com/) or entirely hand-written static HTML.

Content:

- [x] What is SaltyRTC
- [x] Why do we need SaltyRTC
- [ ] How to install
- [ ] How to use
- [ ] Link to demo app
- [ ] How to contribute
- [ ] How to report security issues (including PGP key)

**Comment by lgrahl** [comment]
I could add content if someone else would do the design (as I'm useless regarding design).

**Comment by dbrgn** [comment]
First draft: https://saltyrtc.github.io/

Source is here: https://github.com/saltyrtc/saltyrtc.github.io

TODO: Custom theme

@lgrahl feel free to add content :) Add static pages in the `content/pages/` directory and news posts in the `content/posts/` directory.

**Comment by dbrgn** [comment]
I added some more content on the start page.

@lgrahl what's your status on this? Also, could you [set up the DNS records for saltyrtc.org](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)?

**Comment by lgrahl** [comment]
I've written a "Why?" page but I still need to refine it a bit. Hopefully I can do this at the weekend. (Sorry for the delay. My studies have become a lot more intense in the last couple of weeks.)

**Comment by lgrahl** [comment]
Issues have been moved to https://github.com/saltyrtc/saltyrtc.github.io/issues
