### ISSUE TITLE
WebRTC Spec Wording

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#105]
> For now, all implementations SHALL use the value 16384 which seems to be the highest amount of kilobytes that can be applied for portable WebRTC data channel communication. An implementation MAY use another value if it can guarantee delivery and reception for messages of that size.

The SHALL and the MAY are conflicting.

Maybe we can simply replace the `SHALL` with a `SHOULD`?

**Comment by lgrahl** [comment]
SHOULD should be fine.

**Comment by lgrahl** [comment]
Resolved by b0da20b
