### ISSUE TITLE
Maximum Message Size Indicator

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#107]
In here: https://tools.ietf.org/html/draft-ietf-mmusic-sctp-sdp-19#section-6

We should probably update the spec that it extracts the maximum message size from the SDP blob. ~~For that to work, the user has to pass the SDP blob (local and remote description of RTCPeerConnection) to us.~~

**Comment by dbrgn** [comment]
I can't quite follow. What would be the implications?

**Comment by lgrahl** [comment]
Right now, we're assuming that [`16384` is the most portable maximum message size](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Task-WebRTC.md#detecting-the-maximum-message-size) and it's simply used as default. However, the SDP blob of `offer` and `answer` exchanges the maximum message size specifically for SCTP, so we can use that.

The client simply needs to look at the SDP blob of `offer` and `answer` when it sends/receives it and extract the maximum message size from it or fall back to `16384` if it can't find it. Thus, the `maximum_message_size` attribute of the WebRTC task data negotiation is not needed anymore.

It pretty much analogue to the `RTCSctpCapabilities.maxMessageSize` attribute of ORTC's data channels.

**Comment by dbrgn** [comment]
That would mean that we could in many cases send larger messages, right? Sounds good!

Can you create a PR with the necessary changes?

**Comment by lgrahl** [comment]
> That would mean that we could in many cases send larger messages, right? Sounds good!

Yep

> Can you create a PR with the necessary changes?

ASAICFST (as soon as I can find some time). :)

**Comment by lgrahl** [comment]
As a follow-up: We should go even further and request API changes in the WebRTC API. This information shouldn't be hidden in a SDP blob as it's vital for implementations.

Edit: [Already there](https://w3c.github.io/webrtc-pc/#idl-def-rtcsctptransport).

So extracting it from the SDP isn't even necessary.

**Comment by lgrahl** [comment]
So far, no browser I've tested has implemented the API or embedded the information in the SDP blob. ~~But we should still add it to the spec, so it's implemented and when the API is ready, it's automatically used.~~ We shouldn't add it to the spec yet as it's unknown what browsers will claim and what's actually supported (see the [*Demystifying the 16 KiB Firefox to Chromium Message Size Limit* section](https://gist.github.com/lgrahl/763a4ba303f900188f8042c5aa810cd9#demystifying-the-16-kib-firefox-to-chromium-message-size-limit)). We don't want to suddenly break our chunking implementation due to false claims of the browser.

**Comment by dbrgn** [comment]
We can currently use the max_packet_size field with custom code instead.

**Comment by lgrahl** [comment]
I don't understand.

**Comment by dbrgn** [comment]
> We shouldn't add it to the spec yet as it's unknown what browsers will claim and what's actually supported

I agree. As a transitional solution, we can simply set the `max_packet_size` field instead of querying `RTCSctpTransport.maxMessageSize` and add support for that in a future protocol version.

**Comment by lgrahl** [comment]
Yes. I think we should experimentally try to use 64 KiB when the Browser is not Firefox to test the negotiation algorithm and to potentially improve performance. This will not be put in the spec but I think it would be a great experiment in the JS implementation. What do you think?

**Comment by lgrahl** [comment]
Oh, and for that to work you would also have to set it in the Java version (as that's Chromium-based anyway and should handle 64 KiB just fine).

**Comment by dbrgn** [comment]
I think the implementation should use safe defaults (16 KiB). The user can always override with custom browser detection.

Once we have some experience on what works and what doesn't, we can still adjust these values.

**Comment by lgrahl** [comment]
Good point. We also have no idea how MS Edge would behave (if they have data channels at some point).

**Comment by lgrahl** [comment]
So, just to clarify why we're not going to resolve this issue yet: We need to wait until browsers have implemented the API change that has already been defined by the W3C working group to retrieve the maximum message size. Then, we need to verify that the browser's claims are actually true to avoid breaking the message chunking.

**Comment by lgrahl** [comment]
@dbrgn I think you've tested 64 KiB for Threema in case a Chromium-based browser is being used, right?

**Comment by dbrgn** [comment]
Yes. The app always requests 64KiB. The client also requests 64KiB unless it's Firefox, then 16.

**Comment by lgrahl** [comment]
Moot because #130
