### ISSUE TITLE
Multiple Server Permanent Keys

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#109]
To allow a transition from one server permanent key to another, a client announces the server's public permanent key it's is going to use in `client-auth`. The server can then either drop the client (if the public permanent key is unknown) or continue. `signed_keys` in `server-auth` would then have to be encrypted by the expected key pair.

**Comment by dbrgn** [comment]
Can you give a use case?

**Comment by lgrahl** [comment]
Private key compromised.

**Comment by dbrgn** [comment]
I still can't follow. Verification is done by the client, so the client needs to get the new permanent key through an independent channel if the server is compromised, right?

**Comment by dbrgn** [comment]
Furthermore, we need to clarify what "compromised" means, as we state that no server trust is necessary.

**Comment by lgrahl** [comment]
*Compromised* means MITM is technically possible (#46) between client and server (in case no TLS is being used). This has no effect on client-to-client message security.

If a key is compromised, you'd simply ship a new one on your website or on mobile app deployment. But deployment is not immediately, so having a short time for transition is required.

**Comment by dbrgn** [comment]
But then you would trust the old, "compromised" server to give you the new permanent key?

**Comment by lgrahl** [comment]
Huh? No, key distribution is done by your deployment. It's not going to be part of our protocol.

The client simply tells the server to select a specific public permanent key for it's signing process. The server then *signs* the `signed_keys` field in the `server-auth` message with the corresponding private permanent key.

**Comment by dbrgn** [comment]
Ah, I think I understand it now. You want to be able to keep the permanent key for reverse compatibility while already deploying a new one?

**Comment by lgrahl** [comment]
Exactly.

**Comment by dbrgn** [comment]
I wonder if it's worth the added complexity. Complexity always means more potential for implementation bugs or misuse of keys. And it makes the protocol harder to understand.

Don't you think simply starting a new server on a different hostname or port and migrating slowly to that would be enough in the rare case of a private key compromise?

**Comment by lgrahl** [comment]
Mhh, well, good point. Maybe we should put these recommendations in a wiki or something? Otherwise, we'll get these questions again at some point.

**Comment by lgrahl** [comment]
On second thought, there's a problem:

Client A has been updated to a different server.
Client B has not received the update yet and thus still uses the old server address.
A and B can't reach each other anymore.

**Comment by dbrgn** [comment]
Crap, that's true.
