### ISSUE TITLE
Handover Disable Request

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#120]
If one of the client informs the other that no handover shall be done, it sets the *handover* field in the task's data to `false`. However, this is not reflected in the section *Signalling Channel Handover*.

**Comment by lgrahl** [comment]
Because this hasn't been specified properly, how do the clients handle this @dbrgn?

**Comment by dbrgn** [comment]
See https://github.com/saltyrtc/saltyrtc-task-webrtc-js/commit/090efae51b3d87fd411040c4ff69de2e8a18117d and https://github.com/saltyrtc/saltyrtc-task-webrtc-java/commit/be4ac2f55ddf71e6bb4dbeea83a677027b6d4bd6.

To summarize:

- If handover is disabled, the user shouldn't send a handover message. If he/she still does, an error will be raised and `false` will be returned to indicate that handover was not initialized.
- If receiving a handover message even though handover is disabled on our side, something's wrong. Reset the connection with a protocol error.

**Comment by lgrahl** [comment]
Alright, I'll add this to the tasks, then you can review it and once its merged we can finally release.
