### ISSUE TITLE
Inconsistency regarding handling of inactive responders

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#125]
In the [new-responder](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#new-responder-message) docs:

> Furthermore, the initiator MUST drop new responders that have not sent any messages to the initiator after 60 seconds.

In the [server-aut](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#server-auth-message) docs:

> Additionally, the initiator MUST keep its path clean by dropping inactive responders (i.e. responders that have not sent a message to the initiator, yet). To achieve that, the initiator MAY store the responders in a FIFO queue and drop the oldest responder that did not send a message to it once the path is congested (253 responders are connected). Another solution would be to drop responders that have not sent any messages to the initiator after 60 seconds. However, a combination of both is RECOMMENDED.

**Comment by lgrahl** [comment]
Maybe this shouldn't be in the message description anymore, so we can have a separate section for the initiators path cleaning which can be referenced.

**Comment by dbrgn** [comment]
Might be a good idea, to make it easier to read.

**Comment by lgrahl** [comment]
@dbrgn For the implementations, the latter description is correct.
