### ISSUE TITLE
Accepting message sources other than 0x00

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#135]
> An initiator SHALL ONLY process messages from the server (0x00). As soon as the initiator has been assigned an identity, it **MAY ALSO** accept messages from other responders (0x02..0xff). Other messages SHALL be discarded and SHOULD trigger a warning.
> 
> A responder SHALL ONLY process messages from the server (0x00). As soon as the responder has been assigned an identity, it **MAY ALSO** accept messages from the initiator (0x01). Other messages SHALL be discarded and SHOULD trigger a warning.

Shouldn't it be mandatory that client messages are accepted after having been assigned an identity?

**Comment by lgrahl** [comment]
Mh, IIRC at least the initiator can ignore other responders if one is already authenticated.

**Comment by lgrahl** [comment]
Easiest would be to just say *SHALL* for both. (I'm really starting to regret those roles.)
