### ISSUE TITLE
Msgpack type for binary data

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#136]
Right now the msgpack type used for binary data is unspecified.

The current client and server implementations all use the [bin format family](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family). In Python, this corresponds to the `bytes` type.

When working on the Rust implementation of the client, I used a 16-element byte array (`[u8; 16]`) to store the cookie. This is serialized to msgpack using the [array format family](https://github.com/msgpack/msgpack/blob/master/spec.md#array-format-family), which is also reasonable. In Python, this corresponds to a list of integers.

We should either require that the `bin` format family is being used for serialization, or we should require that both server and client implementations can handle both. The first option is probably the most pragmatic approach.

**Comment by dbrgn** [comment]
Ah, actually the `bin` format is more compact than `array` (bin 8 requires 2 bytes of overhead while array 16 needs 3 bytes), so I think that makes it even more clear.

**Comment by lgrahl** [comment]
Yep, let's go for `bin`. Just need to specify it in the spec now.
