### ISSUE TITLE
Which message is being sent if both peers trust each other

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#15]
In case a token is being used, the responder starts sending a 'token' message. But who sends which message (first) if both peers trust each other?
- [x] Who sends which message (first) if both peers trust each other?
- [x] Clarify what must happen in case one peer does not trust the other.
- [x] What happens if the initiator did not expect a token message (the responder is already trusted)
- [x] What happens if the initiator did not expect an key message (the responder is not trusted)

**Comment by lgrahl** [comment]
The responder will start sending a **key** or **token** followed by a **key** message as soon as he receives a **new-initiator** message from the server or the _initiator-connected_ field in the **server-auth** message was `true`.

Resolved by 56e4408

**Comment by lgrahl** [comment]
We still have to describe what must happen in case...
- the initiator did not expect a **token** message (the responder is already trusted)
- the initiator did not expect an **key** message (the responder is not trusted)

For both cases, the easiest way would be to drop the responder by a **drop-responder** message. Any other suggestions?

**Comment by dbrgn** [comment]
It depends. What if the initiator still trusts the responder, but the responder has forgotten/removed/lost the initiator key? We probably don't have a way to cover both cases, because the initiator either needs to transfer the access token, or do a connection attempt using the trusted key.

I agree that a drop-responder message would probably be the best solution. We can't pass a drop reason to the responder, can we?

In any case, _the application_ should probably fall back to creating a new session (with an auth token) when connection using trusted keys fails. We can't really implement our own fallback in the protocol, can we?

**Comment by dbrgn** [comment]
Another option would be a protocol error. That's already what happens in the current implementations, because the received message type does not correspond to the expected message type according to the handshake state.

@lgrahl what do you think?

**Comment by dbrgn** [comment]
What also needs to go into the spec:
- When the initiator trusts a peer, on receiving the `key` message, the trusted public key should be used to decrypt the message. If decryption fails, the responder should be dropped instead of disconnecting with a protocol error.

Do you agree, @lgrahl?

**Comment by lgrahl** [comment]
'drop-responder' with a reason sounds good to me. I'll add an optional reason to that message. The server then just closes the connection with a different close code than 3004. Both cases can be covered that way because it will be unencryptable data for the initiator in both cases.

We cant implement a fallback procedure. The application should be able to handle those cases as they will occur frequently.

To your last question: How can the initiator differentiate between that case and a responder who tries to send a 'token' message?

**Comment by dbrgn** [comment]
That _is_ the case where the responder tries to send a token message :) Or did I mis-understand your questino?

**Comment by lgrahl** [comment]
Yeah, basically this is just one case to the initiator. To sum it up: When the initiator can't decrypt the first C2C message of the responder (initiator expected 'key' or 'token') it drops the responder with "Can't decrypt that stuff, mate!"

**Comment by dbrgn** [comment]
Yeah, sounds about right. But _is_ that a protocol error or not?

**Comment by lgrahl** [comment]
It is a protocol error, but on C2C messages the initiator should probably not disconnect before the authentication of the responder is complete.

**Comment by lgrahl** [comment]
So... let's just call that a failed authentication attempt.

**Comment by lgrahl** [comment]
The current spec describes that protocol errors for C2C messages are handled differently:
- If the other client is not authenticated yet, an initiator SHALL drop the corresponding responder by sending a 'drop-responder' message with the responder's address in the _id_ field to the server and a close code of `3001` (_Protocol Error_) in the _reason_ field. A responder SHALL close the connection to the server with a close code of `3001`.
- If the other client is authenticated, both initiator and responder SHALL send a 'close' message to the other client containing the close code `3001` (_Protocol Error_). Both SHALL close the connection to the server (normal close code).

The reason behind that behaviour: Bad clients could send rubbish to the initiator before authentication is complete. So, the initiator should not close. However, if the responder has been authenticated towards the initiator, there's no point in continuing once a protocol error has occurred.

**Comment by lgrahl** [comment]
Should be properly described in the spec now. Reopen if needed, @dbrgn.
