### ISSUE TITLE
What is close code 3003 "Handover of the Signalling Channel" being used for?

### ISSUE THREAD

**Issue by ghost** [saltyrtc/saltyrtc-meta#157]
Why there is ```3003: Handover of the Signalling Channel``` Close Code ?

It is not used anywhere in the [Protocol](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md), I found it only in ```SaltyRTC WebRTC Task Protocol``` & ```SaltyRTC ORTC Task Protocol``` that are supersets of original ```SaltyRTC Signalling Protocol``` or I am missing something ?

**Comment by dbrgn** [comment]
The code 3003 is used by tasks that want to hand over the signaling channel to another transport. For example, the WebRTC task allows to hand over the signaling from the WebSocket to a DataChannel.

Does that answer your question?

**Comment by lgrahl** [comment]
@dbrgn answered the question, so I'll close. :slightly_smiling_face:
If you have further questions, feel free to participate in our Gitter chat: https://gitter.im/saltyrtc/Lobby
