### ISSUE TITLE
Questions about the protocol

### ISSUE THREAD

**Issue by ovalseven8** [saltyrtc/saltyrtc-meta#161]
While reading the SaltyRTC protocol description I was not sure about some protocol parts. I'd like if the document could describe the motivation behind some decisions and why it's done this way.

The following points are not entirely clear to me:

- Why isn't it enough to just securely exchange the initiator's public permanent key? Can someone explain the reasoning behind the authentication token generated by the initiator?
- Why isn't the `token` message encrypted with the public permanent key of the initiator?
- Cannot the `token` and `key` messages be combined? So the responder would only send one message instead of two.

Another question:
The presence of both `Sequence number` and `Overflow number` is unnecessarily complicated IMHO. Would not it be possible to expand the `src` and `dest` fields to two bytes, add two bytes to the `counter` and remove 4 bytes from the `cookie`?

So, we have 8 bytes for the counter, which should not be a problem anymore for different programming languages. The source and destination fields now have place for 2^16 values instead. The cookie field is only 12 bytes long now, but that should be enough too?
(or alternatively keep 16 bytes for the cookie and only 4 bytes for the counter?)

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
|                            Cookie                             |
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|           Source              |       Destination             |  
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                             Counter                           |
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by lgrahl** [comment]
#### Auth Token

The initiator has its public key but it doesn't know the responder's public key. Due to how NaCl works, without the responder's public key, we can't derive a secret to decrypt anything. The token thus allows to make a one-way exchange instead of a two-way exchange (making it less annoying for the user).

The token is not encrypted because how would you decrypt it?

We cannot combine `token` and `key` because they don't use the same keys for encryption. But it doesn't matter since `key` directly follows `token`. There's no additional RTT here.

#### Combined Sequence Number

We aren't exactly proud of the combined sequence number but the nonce of NaCl boxes is 24 bytes. It would have been more complicated to add additionally authenticated data with an AEAD construction. Removing more randomness by taking it from the cookie seems risky. Going with *just* 32 bit seemed risky, considering that the sequence number is specified as cryptographically random to increase randomness of the nonce.

That being said, if you take a look at the Python server implementation, it's not really complicated. Also, as a funny side note, JavaScript does not understand the concept of 64 bit unsigned integers...

**Comment by ovalseven8** [comment]
> Due to how NaCl works, without the responder's public key, we can't derive a secret to decrypt anything.

Missed that, thanks. :)

> Removing more randomness by taking it from the cookie seems risky. Going with just 32 bit seemed risky, considering that the sequence number is specified as cryptographically random to increase randomness of the nonce.

I do not fully understand why you want the nonce to be cryptographically random. As long as it's only used once it should be okay, even if it's only "1", "2", "3", etc.

**Comment by lgrahl** [comment]
> I do not fully understand why you want the nonce to be cryptographically random. As long as it's only used once it should be okay, even if it's only "1", "2", "3", etc.

Because the permanent keys are permanent. :wink:

**Comment by ovalseven8** [comment]
> Because the permanent keys are permanent. wink

True, but when you use the same nonce for ANOTHER shared key, it does not matter. Sorry, perhaps you can elaborate. 😳

**Comment by lgrahl** [comment]
Yeah, but you don't. The initiator's permanent key and the responder's permanent key are exactly that, permanent **across multiple connections**. Therefore, it's a problem if you reuse a nonce.

**Comment by ovalseven8** [comment]
I thought a little bit and wonder if not it makes sense to change the permanent keys to Ed25519 signing keys?

My idea:

Each peer has a Ed25519 permanent key.

When the Initiator connects to the Server, the signaling path is the public permanent Ed25519 key. Now, we add a (with the Ed25519 key signed) ephemeral public Curve25519 key to the URL. Why? It signals the server that it should use this key to communicate with the Initiator. In case the server has also a permenent Ed25519 key, it will sign the 'server-hello' message with it and send (unchanged) the server's ephemeral key with it.

The 'client-auth' message should then be encrypted with the client's and server's ephemeral keys.

What has changed?
The SaltyRTC website tells "zero trust towards the server is needed". Forward Secrecy is, however, only guaranteed if the server really creates a new session key when the client connects (what could not be the case because of various reasons, like implementation errors). Now, also the client has influence.

Furthermore, because the encryption keys are not permanent anymore, we can get perhaps simplify the nonce (currently Cookie, Source, Destination, Overflow Number, Sequence Number).

What else could be changed?

When the responder connects to a signaling path, he too should add a ephemeral public Curve25519 key to the URL. However, he cannot sign it with the signing key of the initiator, so we know it's a responder (we get rid of the 'client-hello' message). When the responder is authenticated to the server, we can also get rid of further messages.

Why?
The Initiator could create a signed Curve25519 keypair in advance and push the public key to the server, which can forward it to the responder in a specified message (e.g. 'server-auth'). The responder can verify it given a secure exchange of the Initiator's public signing key.
Now, we can combine the 'token', 'key' and 'auth' messages sent from the Responder to Initiator. Let's say it's called 'key-auth'. It can be encrypted with the Responder's ephemeral Curve25519 secret key and the Initiator's public key for the responder.
The ephemeral public key of the Responder can be included unencrypted, so that the Initiator can decrypt the message.

If everything works, the Initiator can send back a 'auth' message to the Responder.

I don't know if it's thought-out, what would you think about it?

**Comment by ovalseven8** [comment]
I thought a little bit and wonder if not it makes sense to change the permanent keys to Ed25519 signing keys?

My idea:

Each peer has a Ed25519 permanent key.

When the Initiator connects to the Server, the signaling path is the public permanent Ed25519 key. Now, we add a (with the Ed25519 key signed) ephemeral public Curve25519 key to the URL. Why? It signals the server that it should use this key to communicate with the Initiator. In case the server has also a permenent Ed25519 key, it will sign the 'server-hello' message with it and send (unchanged) the server's ephemeral key with it.

The 'client-auth' message should then be encrypted with the client's and server's ephemeral keys.

What has changed?
The SaltyRTC website tells "zero trust towards the server is needed". Forward Secrecy is, however, only guaranteed if the server really creates a new session key when the client connects (what could not be the case because of various reasons, like implementation errors). Now, also the client has influence.

Furthermore, because the encryption keys are not permanent anymore, we can get perhaps simplify the nonce (currently Cookie, Source, Destination, Overflow Number, Sequence Number).

What else could be changed?

When the responder connects to a signaling path, he too should add a ephemeral public Curve25519 key to the URL. However, he cannot sign it with the signing key of the initiator, so we know it's a responder (we get rid of the 'client-hello' message).

Furthermore, in the 'token' message we would transmit the Responder's public signing key. Also, what about when the Initiator pushed public and signed Curve25519 keys to the server? The server could give them to the Responders in e.g. the 'server-auth' message. Now, we can combine the 'token', 'key' and 'auth' message from the Responder to Initiator, saving a round-trip. The combined message would be encrypted using the secret (authentication token).

In the 'auth' response from the Initiator to the Responder, we can encrypt it using the Initiator's pre-shared key the Responder got from the Server and the Responder's ephemeral key.

I don't know if it's thought-out, what would you think about it?

**Comment by lgrahl** [comment]
> The SaltyRTC website tells "zero trust towards the server is needed". Forward Secrecy is, however, only guaranteed if the server really creates a new session key when the client connects (what could not be the case because of various reasons, like implementation errors). Now, also the client has influence.

It is correct that the initiator (and only the initiator) does not have an ephemeral key for the transport encryption towards the server. Something we could change. But I wouldn't do it in the way you've described it because it's incompatible with the existing architecture. I also wouldn't say that this breaks *zero trust* because there's nothing the server can do here to in regards to client-to-client messages, beyond DoS and storing encrypted messages of course. Also, keep in mind that there is very little interaction with the server itself because most messages are simply relayed and encrypted with the client's ephemeral keys.

> When the responder connects to a signaling path, he too should add a ephemeral public Curve25519 key to the URL. However, he cannot sign it with the signing key of the initiator, so we know it's a responder (we get rid of the 'client-hello' message).

Getting rid of `client-hello` would not yield an advantage since `client-auth` is still required. Again, `client-hello` does not add an RTT.

> Also, what about when the Initiator pushed public and signed Curve25519 keys to the server? The server could give them to the Responders in e.g. the 'server-auth' message.

Storing anything on the server would add quite some complexity for the server implementation. Parts of this protocol are already unnecessarily complex. :slightly_smiling_face:

I do appreciate your thoughts but please keep in mind that, at this stage, the protocol is practically finished and deployed on a whole lot of clients. Unless there are major flaws discovered we are not going to make any substantial changes to this version of the protocol. SaltyRTC v2 is a whole different story but I'd start from scratch here and throw out the roles for example.

**Comment by ovalseven8** [comment]
> I do appreciate your thoughts but please keep in mind that, at this stage, the protocol is practically finished and deployed on a whole lot of clients.

For the sake of interest: Do you know of other users of SaltyRTC other than Threema?

And one more question:
In the way SaltyRTC is used for Threema (the web client), there is basically always the initiator and one responder. However, SaltyRTC has the `source` and `destination` fields in its header, so there can be multiple responders to one initiator. Is this being used somewhere or why is this functionality provided? For more flexibility?

**Comment by lgrahl** [comment]
> For the sake of interest: Do you know of other users of SaltyRTC other than Threema?

No.

> And one more question:
> In the way SaltyRTC is used for Threema (the web client), there is basically always the initiator and one responder. However, SaltyRTC has the `source` and `destination` fields in its header, so there can be multiple responders to one initiator. Is this being used somewhere or why is this functionality provided? For more flexibility?

It's not used by Threema but it's something others can make use of.

**Comment by dbrgn** [comment]
> > For the sake of interest: Do you know of other users of SaltyRTC other than Threema?
> 
> No.

We've seen questions about SaltyRTC usage in our Gitter channel though. So there might be people that use it actively, although that's of course not something we can log / know unless people tell us.

**Comment by lgrahl** [comment]
@ovalseven8 Sorry I'm hijacking this thread for it but I couldn't find any other way to contact you. Have you seen [this](https://threema.ch/content/android_developer-2019.pdf)? You can contact me via https://threema.id/MSFVEW6C if you want to talk. :slightly_smiling_face:
