### ISSUE TITLE
Packet: 'send-error', Sequence Number or Hash?

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#19]
Currently, the 'send-error' message contains a SHA-256 hash of the message that could not be relayed by the server. I'm not completely sure if it would make more sense to send the **Channel Number** and the **Sequence Number** instead. Please, comment!

**Comment by lgrahl** [comment]
@dbrgn Any thoughts?

**Comment by dbrgn** [comment]
That would work too, and it would not require the calculation of hashes.

The send-error package is encrypted, right? So sending the sequence number instead of a hash would not give away any information, correct?

**Comment by lgrahl** [comment]
Yeah, `send-error` is encrypted. Then let's use _source_ and _destination_ address, _overflow number_ and _sequence number_ (e.g. the remaining byte sequence of the nonce after the cookie) - we could call that the **message id**. In essence: `nonce[16:]`.

``` js
{  
   "type": "send-error",
   "id": b"000000000000000f"
}
```

**Comment by dbrgn** [comment]
I'd be careful with introducing yet another concept (the message id). Things are getting very complex :) On the other hand it's probably easier to handle a single identifier instead of multiple serialized fields.

So let's go for it.

**Comment by lgrahl** [comment]
That's just a name to outline the various fields. But if you think it's too complex to introduce yet another name, we could also name it something like _nonce_fragment_?

**Comment by dbrgn** [comment]
No, I think message id is fine.
