### ISSUE TITLE
Paket Types: Encrypted / Unencrypted

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#21]
Right now the mechanism to differentiate between encrypted and unecrypted packets is trial-and-error, since there is no prefix that allows the server to differentiate between the two pakets.

First of all, trial-and-error might be inefficient in some implementations. But the other aspect is that you cannot stream the data directly into a parser, because of the possible need for re-parsing. That means that you need to allocate memory to store the message, then you can try to decrypt it, and if that fails, parse it directly as msgpack.

But if we would add a type flag (e.g. a "flags" byte in the beginning) the implementation could differentiate the two packet types without any lookahead. That allows you to "stream" the bytes directly into the parser/decoder, without any allocation.

In Python terms, you could still follow the EAFP principle by trying to decrypt `data[1:]` and falling back to parsing the data as msgpack.

**Comment by lgrahl** [comment]
The only thing about leading bytes before a NaCl Box is that they cannot be authenticated (see #16). However, for 'type' indication I can't think of a reason why it must be authenticated. Still, I might be wrong...

Currently, there is only a one packet window where this trial-and-error technique must be used (after `server-hello`). In every other case it is clear whether a packet must be encrypted or not. An unauthenticated _packet type byte_ in combination with a _dirty_ implementation that does only follow the _packet type byte_ might end up as a security issue.

**Comment by dbrgn** [comment]
I agree.

**Comment by lgrahl** [comment]
One more comment: If the first byte of the packet is
- between 0x80 and 0x8f and the length of the packet is 57 bytes (fixmap)
- or 0xde (map 16)
- or 0xdf (map 32)

it is probably a MsgPack object in plaintext as we are always using maps for our messages. (See the [MsgPack spec](https://github.com/msgpack/msgpack/blob/0b8f5ac67cdd130f4d4d4fe6afb839b989fdb86a/spec.md).) This should help implementations that might be inefficient when using trial-and-error.
