### ISSUE TITLE
WebSocket close codes

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#25]
The WebSocket protocol allows us to close a connection with a specific close code. The code range [3000..3999] can be used for libraries and frameworks.

Proposed close codes:
- 1001: _CLOSE_GOING_AWAY - The endpoint is going away, either because of a server failure or because the browser is navigating away from the page that opened the connection._ Already defined by the WebSocket spec. We use it on the server side to let the client know that the server is being shut down.
- 1002: _CLOSE_PROTOCOL_ERROR - The endpoint is terminating the connection due to a protocol error._ Already defined by the WebSocket spec. We use it to let the peer know that no shared sub-protocol could be found.
- 3000: Path full error (no free responder byte)
- 3001: Protocol error (invalid message, invalid path length, ...)
- 3002: Internal error (syntax error, ...)
- 3003: Handover of the signalling channel (e.g. a data channel when using WebRTC/ORTC)
- 3004: Dropped by initiator (for an initiator that means another initiator has connected to the path, for a responder it means that an initiator requested to drop the responder)
- 3005: Initiator Could Not Decrypt (sent when the initiator could not decrypt the first message sent by the responder - usually indicates out of sync between key trusting between initiator and responder)

See: https://github.com/saltyrtc/saltyrtc-server-python/blob/ac0988a80b1e2bd7e4df67c668d92ce511e94bcd/saltyrtc/common.py#L31:L35

**Comment by dbrgn** [comment]
I implemented these codes in the JS client library.

I think we could put them in the spec for now?

**Comment by lgrahl** [comment]
@dbrgn: 3003 has been changed to _Handover of the signalling channel (e.g. a data channel when using WebRTC/ORTC)_
Basically it is a generic error code where each task has to describe whether it is valid and what should happen.

**Comment by lgrahl** [comment]
Server updated: saltyrtc/saltyrtc-server-python@1f70682098bdc9167ddfe22eb1e515a342aca60f
