### ISSUE TITLE
Negotiations in client-auth and server-auth

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#31]
We would like to introduce negotiable parameters that are being sent in `client-auth` and `server-auth`:
- [x] Keep alive interval (integer in the range of 1.. seconds) in `client-auth`.
- ~~Task (required)~~ (makes no sense between client and server)

**Comment by lgrahl** [comment]
@dbrgn Do you think having a keep alive would make sense? Personally, I think the clients should just send a ping themselves if they want to keep alive the WS connection. I know that the previous Java client I've used for the Web Client prototype was not able to send pings which was the original reason to have keep alives. Maybe we should just wait out the big beta test and then decide if we need it?

**Comment by dbrgn** [comment]
Right now we configured our SaltyRTC server (proxied behind Nginx) to set a keep-alive value of 5 minutes IIRC. After that the website needs to be refreshed. But pings would probably make sense. I'd leave that to the client library implementation though. Or do you see any advantages in negotiating these parameters?

The Java library used supports PING/PONG messages: https://github.com/TooTallNate/Java-WebSocket/issues/213

**Comment by dbrgn** [comment]
Note that the Websocket is only open during connection build-up. So the only time we're waiting for more than a few seconds is when waiting for the initiator/responder to connect. Not sure if it's useful to do that for more than a few minutes. (Although some use cases might profit from it...)

**Comment by lgrahl** [comment]
The only advantage of negotiating this would be for clients that don't support sending ping messages on their own - [for example the browser WS API offers no method to send pings](http://stackoverflow.com/a/10586583). It's not well defined how the connection is kept alive here between client and server.

It wouldn't take a lot of effort to implement this in the server though. And the message change to 'client-auth' is negligible. (In fact, this isn't even a negotiation as the server simply accepts the request to keep alive.)

**Comment by lgrahl** [comment]
It's already implemented and active in the server. However, the message _field_ is not. So, I might actually add this one as an optional feature for servers.
