### ISSUE TITLE
Specify Case of WebSocket Path

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#36]
The spec only says that the path should be the hex encoded public key of the initiator.

It does not specify whether the letters in the hex string should be upper- or lowercase though.

**Comment by lgrahl** [comment]
Indeed.

I propose a MUST for lowercase when connecting to a SaltyRTC server and a MUST for the server to convert to lowercase before validating the path (in case a client misbehaves).

**Comment by lgrahl** [comment]
Resolved in 1c65da3137c4c7cc5a0a4da2e090b008140d3732, see https://github.com/saltyrtc/saltyrtc-meta/blob/1c65da3137c4c7cc5a0a4da2e090b008140d3732/Protocol.md#signalling-path
