### ISSUE TITLE
Create client library checklist

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#39]
Checklist with entries like the following:
- Support all handshake message types
- Support correlating send-error to sent messages
- Support re-sending of messages after a send-error occurred
- Nonce is always validated
- Separate CSN for each connection
- Handover requires ice connection state to be CONNECTED
- ...

Then we can "rate" client libraries using that checklist and create a support matrix. It's also useful for people that want to write new libraries.

**Comment by lgrahl** [comment]
This checklist is probably pretty old by now - we should update it or consider closing the issue if the protocol is _short_ enough to validate an implementation.

Do you think this should make it into the spec or is it just an internal checklist for us?

**Comment by dbrgn** [comment]
Hm, I don't think it should be in the spec. It _could_ be a separate document as a post-implementation checklist. But I think the spec now already contains a lot of implementation notes.

**Comment by lgrahl** [comment]
I agree, the spec is pretty precise. Agree to close?

**Comment by dbrgn** [comment]
Yes.
