### ISSUE TITLE
Bundle Candidates

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#4]
In the browser, each ICE candidate triggers an event. To prevent sending signalling messages for every single ICE candidate, browser implementations should wait a very short amount of time and bundle candidates before they are being sent.

**Comment by lgrahl** [comment]
Is 10 ms acceptable (long enough to catch immediate consecutive events but short enough so the user won't notice the delay)?

**Comment by lgrahl** [comment]
I've decided to not specify a timeout or anything like that. It is just recommended to bundle candidates in general. Here's how I would do it in the browser:
1. On candidate event, add the candidate to the bundled list and use `setTimeout` with a timeout value of `0` to just enqueue the function at the end of JS's event loop
2. Check if a new candidate event has been raised in the meantime.
   - Yes: Use setTimeout again with a timeout value of `0` and continue with 2.
   - No: Send the bundled candidates.

However, this only suits the browser version (needs to be tested, though) as the browser uses event callbacks for candidates. But usually a bunch of candidates arrive at the same time, so enqueuing at the end of the event loop should do the trick.

**Comment by lgrahl** [comment]
@dbrgn You could test that out if you want to - for the browser implementation. :)

**Comment by dbrgn** [comment]
@lgrahl sounds fine. I'll try.
