### ISSUE TITLE
Repeating messages after 'send-error'

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#40]
Add this to the protocol:

> A client MUST repeat messages after a `send-error` response from the server **at least once** but SHOULD send it `n` times.

Reason: When a handover occurs in some tasks (WebRTC, ORTC) a message may be lost on the signalling channel. After a `send-error` the message will be repeated at least once over the now established signalling channel the original signalling channel has been handed over to.

We should specify `n`.

**Comment by dbrgn** [comment]
Could there be cases where re-sending is not desired or helpful?

**Comment by lgrahl** [comment]
For example on the _signalling data channel_. Once the data channel closes, the peer will not be reachable any more.

**Comment by dbrgn** [comment]
Unless the task switched to yet another signaling channel.

Also, what if the message history buffer contains 10 entries, but 15 messages were sent between the faulty message and the send-error rresponse? Then the client cannot repeat the message even though it MUST.

Edit: If the peer is already on the signalling data channel, it won't receive any send-error messages from the server for these messages.

**Comment by lgrahl** [comment]
Well, the channel itself is reliable so that is probably an unrecoverable error? Also, we haven't really talked about this yet but resending leads to unordered messages which could be a problem.

**Comment by dbrgn** [comment]
> Also, we haven't really talked about this yet but resending leads to unordered messages which could be a problem.

Yes. I think I'd favor an approach where the handshake flow (peer - server and peer - peer) is properly covered by the client library itself (including appropriate re-sending), but where the handling of task-level send errors is left to the implementor of these tasks.

**Comment by dbrgn** [comment]
This is how I'd handle the data message errors: https://github.com/saltyrtc/saltyrtc-client-java/pull/9

**Comment by lgrahl** [comment]
What happens in case a `send-error` occurs during the handshake (e.g. before the tasks take action)?

**Comment by dbrgn** [comment]
That should be handled by the core client library (there's still a TODO in the code).

**Comment by dbrgn** [comment]
In the client library, I'd say that re-sending a core (e.g. auth, token, etc) message MUST be retried at least once, but SHOULD be retried 3 times. What do you think?

**Comment by lgrahl** [comment]
I don't know whether the unordered messages would lead to a problem at particular points of the message flow. I'll need to think about this.

**Comment by dbrgn** [comment]
That depends on the implementation. It might reduce parallelism a bit. But in almost all stages of the handshake, the client waits for a certain type of message and won't continue before receiving it.

**Comment by lgrahl** [comment]
Repeat up to three times, each time after a `send-error` message has been received. Only for client-to-client messages.
