### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [saltyrtc/saltyrtc-meta#43]
You should consider signing git commits & releases.
- [onionshare#221 (comment)](https://is.gd/7vU4oK)
- It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
- Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
- And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

---

Of course this issue applies for all repos of SaltyRTC, I just posted it here once.

**Comment by dbrgn** [comment]
I like signing release tags. Don't think there's much use in signing every commit. Git already offers integrity through the commit hashes. And by signing a known-good tag, a user can be sure that all commits leading up to that tag are good.

**Comment by rugk** [comment]
Well.. in any way signing commits certainly does not hurt.

Also read this famous story: https://mikegerwitz.com/papers/git-horror-story
It contains some arguments why signing commits is good. (As already linked in the first posts [here](https://is.gd/7vU4oK) there are some ideas how to do it properly.)

**Comment by dbrgn** [comment]
One of the arguments against (for me) is that I need to enter my long gpg passphrase for every commit. The alternative is to have an always-unlocked gpg agent. That's not something I want to have running all the time. Especially for something that does not really give any added value.

Linus doesn't like commit signatures either: http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html#a2583316

**Comment by dbrgn** [comment]
I'll close this with the suggestion that we gpg-sign release tags, once we're stable.
