### ISSUE TITLE
You need an icon/logo

### ISSUE THREAD

**Issue by rugk** [saltyrtc/saltyrtc-meta#44]
I think you need an icon for SaltyRTC. E.g. for using it in the GitHub organisation... :smiley: 

And for making SaltyRTC popular. :rocket: :wink:

**Comment by lgrahl** [comment]
[We kind of have an idea for a logo.](https://abload.de/img/img_20150804_14230168j6ukl.png)

**Comment by dbrgn** [comment]
Alternatively we could also do something with a salt shaker and bits coming out of it, or something like that.

If none of us is good with logo design (I'm certainly not), we can ask 2-3 people on https://fiverr.com/, and then we should have enough drafts. (Vector version usually costs 5-10$ more once we have a good draft.)

**Comment by lgrahl** [comment]
I'm terrible in doing any kind of art. Above was a quick draft from my girlfriend.

Don't want to insist on it... and it's going to make it more difficult... but I sort of have the feeling there has to be a bear (face) in it. :sunglasses:

**Comment by dbrgn** [comment]
Could she create a draft suitable as logo?

**Comment by rugk** [comment]
> but I sort of have the feeling there has to be a bear (face) in it. :sunglasses:

Why not... and salt of course. :rice_ball:*

\* Yes, I know this is not salt...

**Comment by lgrahl** [comment]
@dbrgn I'll ask her. I also really like the idea of having a salt shaker.

**Comment by rugk** [comment]
But if you use a salt shaker _and_ a bear it may be too much. Especially when you view the icon in a small size.

**Comment by lgrahl** [comment]
[Got a new icon proposal](https://abload.de/img/_20160904_115130gssbx.jpg). What do you think? I guess it's a bit too detailed but I like the idea. Play around with it.

**Comment by dbrgn** [comment]
Looks cool as artwork, but that will never work at 16x16px :)

**Comment by rugk** [comment]
Maybe the 16x16 version could be an alternative, small icon e.g. only showing the salt shaker.

**Comment by IndianaDschones** [comment]
I made an minimalistic logo (material design style). Including a salt shaker, a bearface and salt ;)

![saltyrtc](https://cloud.githubusercontent.com/assets/6652142/18234445/0b5fbe66-7306-11e6-9360-d07a0049f7db.png)

**Comment by lgrahl** [comment]
I might get some more drafts in the next days.

**Comment by lgrahl** [comment]
Based on the proposal above, my girlfriend has made another draft:
![logo saltyrtc](https://cloud.githubusercontent.com/assets/1793755/19013974/1af86158-87e1-11e6-9909-0ad8a6d8fe01.png)
I can't put my finger on it but I'm not entirely happy with it. Something about the font, edges are a bit _rough_, maybe more salt grains, maybe the bear face is a little big, maybe black & white is a bit too much contrast? And the icon proposal on the right seems a bit empty. I really don't know. I wanted to get rid of the _RTC_ part which seemed to big. Can we work something out based on this? (My girlfriend has other stuff to do and my vague conception isn't helping either :wink:, so I think we should ask someone else here)

**Comment by rugk** [comment]
Personally I like the cyan/green version proposed previously better.
I agree that the last image looks not optimal.

**Comment by dbrgn** [comment]
As a very different idea, what about something based on this?

http://www.freepik.com/free-vector/try-our-extra-salty-products_822392.htm#term=salt&page=1&position=4

![img](https://image.freepik.com/free-vector/try-our-extra-salty-products_1045-32.jpg)

We could adapt it to say "Try our Extra Salty RTC". And change the 20c to "Free".

And for the small icon, we could take just the salt shaker.

Unfortunately I don't have an Illustrator installation right now and the file doesn't open properly in Inkscape. But friends do.

**Comment by lgrahl** [comment]
That's pretty cool. We could remove _Try our_ and _Products_ to get a square that works for our GitHub avatar. We'll have to squeeze in a bear face somewhere, maybe very subtly as the background of _20c_/_Free_. Note that we will have to attribute them.

**Comment by lgrahl** [comment]
To get the _RTC_ in there, we could remove _Extra_, replace it by _Salty_ and place the _RTC_ where _Salty_ was.

**Comment by dbrgn** [comment]
For places like the Github picture, which is quite small, I'd only use the salt shaker. Otherwise it's hard to read at first glance.

I'll try to get my hands on a copy of Illustrator.

**Comment by lgrahl** [comment]
I'll do my best to convert the bear face above to a vector graphic. Will be fun. :sweat_smile:

**Comment by dbrgn** [comment]
It's easy in Inkscape: Path > Trace Bitmap

**Comment by lgrahl** [comment]
I think I pretty much nailed it!
![bear](https://cloud.githubusercontent.com/assets/1793755/19038129/63d06976-897a-11e6-9b22-f4c3a597fb5b.png) ([as SVG](https://gist.github.com/lgrahl/be0e3ad312011fda7e2543c7a65eaa74))

**Comment by lgrahl** [comment]
![free_bear](https://cloud.githubusercontent.com/assets/1793755/19039768/8b0391e2-8981-11e6-9e70-30f882b470f0.png)
[SVG](https://gist.github.com/lgrahl/be0e3ad312011fda7e2543c7a65eaa74#file-bear_free-svg)

**Comment by rugk** [comment]
This is how the free versions looks here (Linux):
![freebear](https://cloud.githubusercontent.com/assets/11966684/19048830/316f0824-89a8-11e6-87c5-2965f8d04d0c.png)

You should choose a platform-compatible font.

**Comment by lgrahl** [comment]
Noticed that already. I don't know if one can embed fonts in SVG.

**Comment by dbrgn** [comment]
You can convert text to a path object.

**Comment by lgrahl** [comment]
Alright, ping me once you need it.

**Comment by lgrahl** [comment]
For the sake of completeness or for inspiration (or because I particularly like this one), here's another previous draft from my girlfriend.

![image](https://cloud.githubusercontent.com/assets/1793755/19075340/c7b7603c-8a44-11e6-8a98-e12ec5234aab.png)

**Comment by dbrgn** [comment]
So how about this? :)

![try_our_rtc_300px](https://cloud.githubusercontent.com/assets/105168/19627336/ea76329c-9944-11e6-8a09-5c551c690ceb.png)

And the small icon:

![try_our_rtc_icon_256px](https://cloud.githubusercontent.com/assets/105168/19627339/f0497166-9944-11e6-9a97-e4a4d37d5026.png)

Thx to http://danielhartmann.ch/ for the vector editing.

**Comment by rugk** [comment]
Looks nice, but the big version can not be used as any icon (not even a large one) - maybe this is a good logo/picture for website/etc.
The small icon looks good.

**Comment by lgrahl** [comment]
Cool! We still need a 16x16 / 32x32 favicon version, right?

**Comment by dbrgn** [comment]
Possible favicons:

![favicon-16](https://cloud.githubusercontent.com/assets/105168/19629246/7154dcde-9970-11e6-92b5-405e8407017d.png)

![favicon-32](https://cloud.githubusercontent.com/assets/105168/19629248/715abad2-9970-11e6-96ad-2dc8fbe4812b.png)

![favicon-64](https://cloud.githubusercontent.com/assets/105168/19629247/715533aa-9970-11e6-836e-a228a79768a2.png)

If you like them I can add a PR to the repo that adds all media files.

**Comment by lgrahl** [comment]
Can you sharpen the lines of the 16x16 one?

**Comment by dbrgn** [comment]
Not sure. It's an SVG -> PNG export, so the aliasing is probably not easy to get rid of.

Here's a Gimp import of the SVG. Not really better.

![favicon-16-gimp](https://cloud.githubusercontent.com/assets/105168/19629336/3920e396-9973-11e6-9604-2f2f07421973.png)

Maybe other tools can scale it better? Otherwise, manual pixel manipulation might be necessary.

**Comment by rugk** [comment]
I'd suggest to to just use SVG when possible. :smiley:  (BTW [Firefox even supports SVGs for favicons](http://caniuse.com/#feat=link-icon-svg))

**Comment by dbrgn** [comment]
And to end the bikeshedding now - @lgrahl are you happy with the general direction of the icon / logo? If yes I'll add a PR that adds the media files to the meta repo. We can still improve it in the future with more PRs.

**Comment by lgrahl** [comment]
16x16 looks a bit like an alien schlong to me but other than that, I'm happy with it for now, yeah!

**Comment by rugk** [comment]
:+1: for (ending) the bikeshedding. :laughing:
