### ISSUE TITLE
Add Introduction

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#52]

**Comment by dbrgn** [comment]
Important:
- [ ] Premise: TLS is broken
- [ ] Why is it necessary?

**Comment by lgrahl** [comment]
I'm thinking of renaming the abstract to introduction and removing the abstract entirely. Partly, because I'm lazy, partly because I think we have everything in the abstract (in the task-webrtc branch). What do you think, @dbrgn?

**Comment by dbrgn** [comment]
Yeah, I think abstract and introduction can be combined.

**Comment by lgrahl** [comment]
@dbrgn The introduction is now complete. Can you have a quick look if something is missing for you?
