### ISSUE TITLE
Message Chunking Spec

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#54]
Although `chunked-dc` is quite a simple format, we should probably write a short specification for it.

The resulting spec should be referenced in the WebRTC and ORTC task.

**Comment by lgrahl** [comment]
@dbrgn Would you like to write a short spec for the chunking?

**Comment by dbrgn** [comment]
Can do next week, probably.

**Comment by lgrahl** [comment]
Anything missing or can this be closed?
