### ISSUE TITLE
Security Mechanisms

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#61]
Complete the _Security Mechanisms_ section.

**Comment by lgrahl** [comment]
@dbrgn Could you glance over the [Security Mechanisms](https://github.com/saltyrtc/saltyrtc-meta/blob/master/Protocol.md#security-mechanisms) section?

**Comment by dbrgn** [comment]
> The initiator either authenticates the responder by receiving the responder’s public permanent key via the authentication token

As the authentication and the public key are independent, "via" is the wrong word here. Maybe you meant "together with"?

**Comment by lgrahl** [comment]
Mhh, I don't know to be honest. This is the easiest way I could find while not having to describe the 'token' message mechanism.

**Comment by dbrgn** [comment]
You don't explain the auth token either :)

**Comment by lgrahl** [comment]
How about

> The initiator either authenticates the responder by receiving the
> responder’s public permanent key encrypted by the authentication token,
> or it already knows the public permanent key of the responder.

?

**Comment by dbrgn** [comment]
Sounds good. I'd change "by the" to "with the" though.

**Comment by lgrahl** [comment]
Done 5df72e4. Anything else? Otherwise, close. :)
