### ISSUE TITLE
Chunked DC

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#66]
The `chunked-dc` chunking should be explained before or at first use in the specification.

**Comment by lgrahl** [comment]
Isn't that the case? https://github.com/saltyrtc/saltyrtc-meta/blob/master/Task-WebRTC.md#wrapped-data-channel-1

**Comment by dbrgn** [comment]
No, `chunked-dc` is mentioned in the first paragraph, but linked only in the fourth (after the bullet points).

**Comment by lgrahl** [comment]
Okay, I get what you mean. Any ideas?

**Comment by lgrahl** [comment]
@dbrgn I've changed the corresponding sections. Can you review them? See 0435d3a

**Comment by lgrahl** [comment]
(Close if it has been resolved for you)

**Comment by dbrgn** [comment]
Looks good to me
