### ISSUE TITLE
WebRTC Task: Handover

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#69]
This sentence is a bit confusing:

> Both clients SHALL send this message once the wrapped data channel's state for the handed over signalling is open on the signalling channel that has been established over the SaltyRTC server.

It should probably be reworded.

> After this message, the client MUST

After sending or receiving?

**Comment by lgrahl** [comment]
Good find! That sentence is awful. Both things should be fixed in 49c38da.
