### ISSUE TITLE
Provide 'subprotocol'

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#7]
A WebSocket client can provide a list of _subprotocols_ when connecting. We should choose a name for the protocol (and probably a version number, too).
- [x] Choose a subprotocol name (including a version number)
- [x] Register in [WebSocket Subprotocol Name Registry](https://www.iana.org/assignments/websocket/websocket.xhtml)
- [x] Spec: Providing a _subprotocol_ is required

Note: We do not need such a mechanism for #3 because the _subprotocol_ will remain the same when switching over the communication channel.

**Comment by lgrahl** [comment]
We should also register ourselves in the [IANA WebSocket Subprotocol Name Registry](https://www.iana.org/assignments/websocket/websocket.xhtml)

**Comment by lgrahl** [comment]
Although the WebSocket Spec recommends a Java-package-like subprotocol name (see [RFC 6455, chap. 1.9.](https://tools.ietf.org/html/rfc6455#section-1.9)), I think it is okay to ignore this recommendation in our case. First of all, we have no domain for this organisation (yet). Secondly, the name _saltyrtc_ is pretty unique.

Let's use `saltyrtc-x.y` where `x` and `y` denote the major and minor version number of the subprotocol. We willl start with version `1.0` which will be frozen as soon as the protocol specification is considered complete. Further protocol changes will increase the major and minor version number where appropriate.

**Comment by lgrahl** [comment]
I think we should also provide information about the signalling type: Currently that is *WebRTC* and *ORTC*.

**Comment by dbrgn** [comment]
I agree about the name. OTOH for the version name, the only other subprotocol that contains a version suffix does not use a separator dash:

ocpp1.2 OCPP 1.2    [http://www.gir.fr/ocppjs/ocpp_srpc_spec.shtml]
ocpp1.5 OCPP 1.5    [http://www.gir.fr/ocppjs/ocpp_srpc_spec.shtml]
ocpp1.6 OCPP 1.6    [http://www.gir.fr/ocppjs/ocpp_srpc_spec.shtml]
ocpp2.0 OCPP 2.0    [http://www.gir.fr/ocppjs/ocpp_srpc_spec.shtml]

Maybe we should use saltyrtc1.0 instead?

**Comment by dbrgn** [comment]
(PS: You should probably get saltyrtc.org :))

**Comment by lgrahl** [comment]
There is another subprotocol called `notificationchannel-netapi-rest.openmobilealliance.org` which has dashes in its name as well. I think we should be fine with `saltyrtc-1.0`.

**Comment by lgrahl** [comment]
Any protest @dbrgn or is `saltyrtc-1.0` fine by you?
Now that we have saltyrtc.org, we could potentially use `org.saltyrtc.1.0` which would follow the WebSocket RFC recommendations.

**Comment by dbrgn** [comment]
I like including the domain, but the RFC doesn't speak about Java package like names. Instead, it uses a subdomain as an example. The already registered subprotocols that use domain names also follow that pattern.

What about `v1.saltyrtc.org`? For minor protocol upgrades there's no need to increase the protocol version (as there's no support for semantic versioning without a clearly specified version indicator). And for major changes we'd switch to `v2`.

**Comment by lgrahl** [comment]
Oh, you're right, they don't use Java package like names.

Yeah, `v1.saltyrtc.org` should be fine.

**Comment by dbrgn** [comment]
Then let's choose that :)

**Comment by lgrahl** [comment]
Uh... let's drop down to `v0.saltyrtc.org` until the spec has been completely reviewed. That way we can rule out that somebody is using an older version. What do you think @dbrgn?

**Comment by dbrgn** [comment]
Good point.

**Comment by lgrahl** [comment]
I've made a WebSocket subprotocol entry request at IANA.

**Comment by lgrahl** [comment]
Registration done! See: https://www.iana.org/assignments/websocket/websocket.xhtml

**Comment by dbrgn** [comment]
Yay :)

**Comment by dbrgn** [comment]
Yay :)

**Comment by dbrgn** [comment]
Yay :)
