### ISSUE TITLE
New Message Type: 'application'

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#87]
I think we should add a message called 'application':

```
{
  "type": "application",
  "data": anything
}
```

This allows user applications to send simple control messages/early data or whatever it desires without having to modify a task. The message can be sent at any time after the client-to-client handshake has been completed. Every task should support it, even after handover. It shall be independent of message states. The message shall not be abused for custom protocols which should be defined as tasks.

(And yes, I think it should land in v1)

@dbrgn Thoughts?

**Comment by dbrgn** [comment]
Haha, there we have the `Data` message again that we dropped :smile: 

What about that simple `DataTask` you mentioned earlier?

**Comment by lgrahl** [comment]
The problem with the data task is that it's a task. Currently, we cannot have multiple tasks being active at the same time. This 'application' message is intended for messages such as a quick version compatibility check of a user application. It may also be used as a workaround for missing messages of a task (ideally, a PR is already open and it's being used in the meantime ;) ).

**Comment by dbrgn** [comment]
> Currently, we cannot have multiple tasks being active at the same time.

That's true, you convinced me :)

**Comment by lgrahl** [comment]
Just to add: For a very strict protocol such as the WebRTC task defines, a custom message will not be that important. However, I'm currently writing on the ORTC task and there definitely will be plenty of use cases where you need to sneak in control messages in between as ORTC is very low level.
