### ISSUE TITLE
Clarification regarding new-initiator message

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#92]
A responder can connect to / await an initiator in two ways:
- Public permanent key and auth token
- Trusted public permanent key

In both cases, the public permanent key of the initiator is the ws endpoint.

That means that a new-initiator message is only plausible if another initiator with the same public/private keypair connects to the endpoint, right? That can only mean that the same initiator reconnected, right?

In the client codebase, would this pseudocode be the right way to handle it?

```
onNewInitiator() {
    publicKey = this.initiator.getPublicKey();
    this.initiator = new Initiator(publicKey);
}
```

(This assumes that the `Initiator` class wraps information like CSN, cooki etc)

**Comment by lgrahl** [comment]
Yes, this is correct as the initiator cannot use a different public key.

Note: Technically, it could happen that the user has cloned the initiator (and its key pair).

**Comment by dbrgn** [comment]
Thanks! Will be implemented in https://github.com/saltyrtc/saltyrtc-client-java/pull/32.
