### ISSUE TITLE
Clarification regarding new-responder message

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#93]
What happens if the client receives a `new-responder` message with an id that is already known? Protocol error?

When does the server start re-assigning already used responder ids? Once the old ones are used up?

**Comment by lgrahl** [comment]
I'd have to look into the server code how the server reassigns IDs but the server does reassign IDs, yes. `new-responder` with the same ID means that the previous one has disconnected, so it's not an error but normal behaviour on the path.

**Comment by dbrgn** [comment]
Ok, so `new-responder` with the same ID will replace the previous responder.

**Comment by lgrahl** [comment]
Do we need to update the spec (if it isn't crystal clear)?

**Comment by dbrgn** [comment]
Would probably be good, yes. I wanted to do it this morning, but didn't find time do do so yet.

**Comment by dbrgn** [comment]
Implemented in https://github.com/saltyrtc/saltyrtc-client-java/pull/32. Protocol PR is at #95.
